<?php
return [
    'localhost' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'local.gaido' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'localhost:9000' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'NOTE-GAIDO' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'DESK-GAIDO' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'gaido.dev' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
    'php81' => [
        'email' => 'luisfernandogaido@gmail.com',
        'senha' => 'wvzyyxmswjqunbrx',
        'nome' => 'Luís Fernando Gaido',
        'de' => '',
        'de_senha' => '',
        'proxy' => false,
    ],
];